repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-xml
      - id: check-toml
      - id: check-docstring-first
      - id: check-json
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: (README\.md|README_ZH\.md)$
      - id: end-of-file-fixer
        files: \.py$
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        exclude: ".*poetry.lock"
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.1.0
    hooks:
      - id: nb-clean
        args: [ --preserve-cell-outputs, --remove-empty-cells ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies: [ tomli ]
        exclude: |
          poetry.lock|
          (\/.*?\.[\w:]+)/pyproject.toml|
          (\/.*?\.[\w:]+)/poetry.lock
        args:
          [
            "--ignore-words-list",
            "astroid,gallary,momento,narl,ot,rouge,nin,gere,asend,ans,thur",
          ]